name: gh-pages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CI: true

jobs:
  run:
    strategy:
      fail-fast: false

    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Set Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - run: node --version
      - run: npm --version

      - name: Install npm dependencies
        run: npm install --omit=dev

      - name: Build static page with slides
        run: npm run build

      - name: deploy gh-pages
        run: npm run deploy
