name: gh-pages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CI: true

jobs:
  run:
    strategy:
      fail-fast: false

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Set Node.js version
        uses: actions/setup-node@v1

      - run: node --version
      - run: npm --version

      - name: Install npm dependencies
        run: npm install # switch to `ci` when Node.js 6.x is dropped

      - name: Build static page with slides
        run: npm build

      - name: deploy gh-pages
        run: npm deploy
